apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.order.arc.bwi.de
spec:
  group: order.arc.bwi.de
  version: v1alpha1
  service:
    namespace: system
    name: apiserver-service
  groupPriorityMinimum: 2000
  versionPriority: 100
